### ISSUE TITLE
Error packaging 'pkg' after project uses 'best require'

### ISSUE THREAD

**Issue by fengcms** [yuezhihan/require-plus#2]
My project uses 'best require', it's work and good.
my code like this:
```js
const bestRequire = require('best-require')
// best-require config
bestRequire(process.cwd(), {
  '@': '~/app',
  config: ':@/config',
  utils: ':@/utils',
  core: ':@/core',
  query: ':core/query'
})
```

but, when i use 'pkg' to packaging my project, it's return Error.
like this:
```bash
$ pkg .
> pkg@4.4.8
> Warning Cannot find module ':config' from '/Users/fungleo/Sites/Github/restful-cms-koa'
  %1: /Users/fungleo/Sites/Github/restful-cms-koa/app.js
> Warning Cannot find module ':utils/tool' from '/Users/fungleo/Sites/Github/restful-cms-koa/app'
  %1: /Users/fungleo/Sites/Github/restful-cms-koa/app/index.js
> Warning Cannot find module ':@/middle/logger' from '/Users/fungleo/Sites/Github/restful-cms-koa/app'
  %1: /Users/fungleo/Sites/Github/restful-cms-koa/app/index.js
> Warning Cannot find module ':@/middle/error' from '/Users/fungleo/Sites/Github/restful-cms-koa/app'
  %1: /Users/fungleo/Sites/Github/restful-cms-koa/app/index.js
> Warning Cannot find module ':config/config-koa-body' from '/Users/fungleo/Sites/Github/restful-cms-koa/app'
  %1: /Users/fungleo/Sites/Github/restful-cms-koa/app/index.js
> Warning Cannot find module ':@/router' from '/Users/fungleo/Sites/Github/restful-cms-koa/app'
  %1: /Users/fungleo/Sites/Github/restful-cms-koa/app/index.js
```
How can I solve this problem？can you help me?

my package.json
```json
{
  "name": "restful-cms-koa",
  "version": "1.0.0",
  "description": "A small restful CMS based on koa framework",
  "main": "app.js",
  "scripts": {
    "dev": "nodemon app.js",
    "start": "node app.js"
  },
  "keywords": [
    "restful",
    "cms",
    "koa"
  ],
  "author": "fungleo",
  "license": "MIT",
  "dependencies": {
    "best-require": "^1.1.4",
    "koa": "^2.11.0",
    "koa-body": "^4.1.1",
    "koa-json": "^2.0.2",
    "koa-log4": "^2.3.2",
    "koa-router": "^8.0.8",
    "koa-static": "^5.0.0",
    "node-rsa": "^1.0.8",
    "sequelize": "^5.21.6",
    "sqlite3": "^4.1.1"
  },
  "devDependencies": {
    "eslint": "^6.8.0",
    "nodemon": "^2.0.3",
    "standard": "^14.3.3"
  },
  "pkg": {
    "output": "restful-cms-koa",
    "targets": [
      "node10-macos-x64"
    ]
  },
  "bin": "app.js"
}
```
> my English is very poor, -_-|||

**Comment by fengcms** [comment]
仔细看了一下，作者是国人。。。我用中文描述一下我遇到的问题吧。
最近正在学习 koa ，感觉引用资源很不优雅，于是找到了这个库，在使用过程中感觉非常愉快。
但是在项目开发完成后，我打算将包编译成二进制，便于在没有node环境的电脑上运行。经过一些资料的查找，准备使用 pkg 来进行打包。
但是在打包的时候，发现其并不支持 `best-require` 这种引用方式。
因此，我现在的问题就变成了这样：
1. 如何配置 `best-require` 可以让 `pkg` 打包支持？
2. 如果不能支持 `pkg` 打包的话，那么有无其他方式可以优雅的解决引用问题？
如果能提供解决方案或者思路，将万分感谢！

**Comment by zhihanyue** [comment]
When using **pkg** with **best-require**, you should change `process.cwd()` to `__dirname` because `process.cwd()` points to the true running path rather than **pkg**'s snapshot path.  Then, specify all the include directories in **pkg**'s `scripts` option. After doing this, the warnings still exists, but don't worry, the hook runs well with **pkg**'s runtime.

**Comment by zhihanyue** [comment]
Here is an example:

**package.json**
```
{
  // ......
  "bin": "index.js",
  "pkg": {
    "scripts": "app/**/*.js"  // include all js files in ./app
  }
}
```

**index.js**
```
const bestRequire = require('best-require')
bestRequire(__dirname, {
    'app': '~/app'
})

require(':app/bbb/ccc/ddd/test')
```

**Comment by fengcms** [comment]
Thank you for your reply. I'll try now. if it's work, I'll come here and close this issues. Thank you!

**Comment by fengcms** [comment]
it's can't work, I try a simple project. like this:

## project tree

```bash
├── config
│   └── index.js
├── index.js
├── package-lock.json
└── package.json
```

## index.js

```js
const bestRequire = require('best-require')
bestRequire(__dirname, {
  config: '~/config'
})

const { a, b } = require(':config')

console.log(a, b)
```

## config/index.js

```js
module.exports = {
  a: 1,
  b: 2
}
```
## package.json
```json
{
  "name": "pkg-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "best-require": "^1.1.4"
  },
  "bin": "index.js",
  "pkg": {
    "scripts": "config/*.js"
  }
}
```
I try with `"scripts": "config/*.js"` or `"scripts": "config/**/*.js"`.

## in node
```bash
$ node index.js
1 2
```

## in pkg
```bash
$ pkg index.js
> pkg@4.4.8
> Targets not specified. Assuming:
  node10-linux-x64, node10-macos-x64, node10-win-x64
> Warning Cannot find module ':config' from '/Users/fungleo/Sites/myWork/GitHub/pkg-demo'
  %1: /Users/fungleo/Sites/myWork/GitHub/pkg-demo/index.js
```

@yuezhihan ... so sad

**Comment by fengcms** [comment]
My system info:
os: mac os 10.15.4
node: v10.20.1
npm: 6.14.4
pkg: 4.4.8
shell: zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by zhihanyue** [comment]
After doing this, the **warnings**, which are **not errors**, still exists. This means your program has been successfully packaged. You can run your packaged program and see if it works.

**Comment by fengcms** [comment]
Yes, it's successfully packaged. But, it's can't run.
The packaged program print **errors** in my shell, like this:

```shell
./index-macos
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module '/snapshot/pkg-demo/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:634:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:560:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at Module.module.exports.module.__proto__.require (/snapshot/pkg-demo/node_modules/best-require/lib/index.js:30:20)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/snapshot/pkg-demo/index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

**Comment by zhihanyue** [comment]
It shows that **best-require** correctly resolved the path to **pkg**'s snapshot. Just make sure your js files is indeed packaged into its snapshot's corresponding path through `scripts`.

**Comment by fengcms** [comment]
Yes! It's my fault.

Can't use `pkg index.js`, it's error.

Use `pkg .`, then success.

Thank You!
